name: Deploy BiteBytes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Build frontend
      working-directory: bitebytes_app
      run: flutter build web

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        scp -o StrictHostKeyChecking=no -r bitebytes_app/build/web/* adminc@172.16.13.105:/usr/share/nginx/html/
        ssh -o StrictHostKeyChecking=no adminc@172.16.13.105 "sudo systemctl restart nginx && sudo systemctl restart bitebytes-backend"